### PR TITLE
Add Proton DApp & Constellation Book

### PR DESCRIPTION
**Pull request by NeutronStarPRO**

### CODE REVIEW

**Comment by domwoe** [comment]
Hey @NeutronStarPRO,

thank you for the contribution. Would you mind adding a new category after "DeFi" for Social applications and add Proton there?

I'd also recommend a more "descriptive description" ;) to the constellation book.

**Comment by NeutronStarPRO** [comment]
Thank you for your thoughtful feedback and suggestions! 

I'll add a new category for Social applications after "DeFi" and include Proton in that section.

**Review by domwoe — APPROVED** [review]
Thank you. That's perfect!

**Review by NeutronStarPRO — COMMENTED** [review]
Thank you @domwoe , I've made revisions to the submission based on your suggestions. 
Please take another look.

**Pull request merged**
